# Generated by Django 2.2.3 on 2019-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='adr_city')),
                ('pincode', models.IntegerField(verbose_name='adr_pin')),
                ('state', models.EmailField(max_length=50, verbose_name='adr_state')),
                ('active', models.CharField(default='Y', max_length=50, verbose_name='active')),
            ],
            options={
                'db_table': 'Address_Info',
            },
        ),
    ]
