# Generated by Django 2.2.3 on 2019-12-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studName', models.CharField(max_length=50, verbose_name='stud_name')),
                ('studage', models.IntegerField(verbose_name='stud_age')),
                ('studemail', models.EmailField(max_length=50, verbose_name='stud_email')),
                ('studfees', models.FloatField(verbose_name='stud_fees')),
                ('studdept', models.CharField(max_length=50, verbose_name='stud_dept')),
                ('active', models.CharField(default='Y', max_length=50, verbose_name='active')),
                ('studAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
            options={
                'db_table': 'Stud_Info',
            },
        ),
    ]
